name: ghbuild

permissions: write-all
on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:

  workflow_dispatch:

jobs:
  call_build:
    uses: TEHIK-EE/smart-base/.github/workflows/ghbuild.yml@main
